name: storybook build

on:
  push:
    branches:
      - main
    paths:
      - "stories/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: git config
        run: |
          git config --global user.name 'ikepu-tp'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: install
        run: npm install

      - name: build
        run: npm run build-sb

      - name: set version
        run: node -p -e '`RELEASED_VERSION=v${require("./package.json").version}`' >> $GITHUB_ENV

      - name: git add
        run: |
          git branch sb-build-${{ env.RELEASED_VERSION }}
          git add ./sb-docs
          git commit -m "storybook build on ${{ env.RELEASED_VERSION }}"
          git push -u origin
